### ISSUE TITLE
Widevine support

### ISSUE THREAD

**Issue by peak3d** [RobRich999/Chromium_Clang#1]
Hi RobRich999,

first thanks for your build, its the only one I found with working widevine.
We at kodi are working on a web view and for evaluation I'm curently trying to get widevine in my own build (latest chromium sources). I remember from a year ago that it was only possible with patching CDM_VERSION. Has this changed?

Would be really great if you can post the necessary changes / steps to get it working!
Seems that only using your args.gn is not the key to luck.

If you prefer email for an answer: pfau@peak3d.de

Thanks again! Markus

**Comment by RobRich999** [comment]
Email reply sent.  :)

**Comment by peak3d** [comment]
thanks, issue is only present for is_component_build=true.
Your args.gn builds well (if one have a build host with enough RAM)

raised an ticket at chromium for this.
