### ISSUE TITLE
[Question] Widevine Support

### ISSUE THREAD

**Issue by EasyNV** [RobRich999/Chromium_Clang#11]
Hi!

Thank you very much that you've taken your time and resources to build this amazing chromium binary, I've a question though if I would like to have a Widevine support on my Chromium can I follow this guide that is stated here https://chromium.woolyss.com/#widevine ?

Or can anyone give me some references on how to add the Widevine Components? Sorry for the noob question 😅

Thank you

**Comment by woolyss** [comment]
Hello @EasyNV, I saw your comment on the woolyss website but I answer you here! ;)

RobRich does not compile Chromium with the Widevine support (cf. GN argument: `enable_widevine = true`). So you cannot use the Widevine plugin on his release. Even if you install the Widevine plugin yourself, I will not work.
Prefer the Hibbiki's or Marmaduke's releases with the Widevine support. They are "Widevine-friendly" ;)

Maybe RobRich can enable the specific GN argument ^^
After that, it could be possible to add the Widevine plugin yourself.

Let's wait for the @RobRich999 answer! ;)

**Comment by RobRich999** [comment]
I think the directions at https://chromium.woolyss.com/#widevine still should work, though it has been quite awhile since last attempting here as I have no use for Widevine DRM in Chromium, so YMMV.

Basically it is just copying a working Widevine directory to the Chromium profile. Let us know if it still works. :)

**Comment by EasyNV** [comment]
Hi @woolyss @RobRich999!

Thanks for the kind comments and explanations 😁

I've tried to copy the Widevine directory to the chromium profile but when I tried to open the `chrome://components` the Widevine plugin is not listed there

It looks like the `enable_widevine = true` argument is needed when compiling just like @woolyss said 😁

Thank you

**Comment by RobRich999** [comment]
Long time, no reply. Apologies. Sadly, enable_widevine = true often produces a broken Widevine component.
