### ISSUE TITLE
[question] is re-activating sync possible?

### ISSUE THREAD

**Issue by eladkarako** [RobRich999/Chromium_Clang#16]
I know the build is dubbed 'no-sync',  
but I've tried to enable sync and log into the google account,  
the browser will not sync stuff at all (settings, passwords, extensions),  
but it will log into the google websites,  
<strong>is sync can not be enabled in any of the builds? (I had previously used [some other builds](https://github.com/macchrome/winchrome/releases) that did allow the sync feature after it was re-enabled in the settings)</strong>

**Comment by RobRich999** [comment]
You will need to generate and add your own Google API keys. Once set as environment variables, sync should work for ya'.

More info here:

https://chromium.woolyss.com/#google-api-keys
