### ISSUE TITLE
v68.0.3401.0 build not 64 bit

### ISSUE THREAD

**Issue by HitomiTenshi** [RobRich999/Chromium_Clang#2]
Build [v68.0.3401.0-r552203-win64](https://github.com/RobRich999/Chromium_Clang/releases/tag/v68.0.3401.0-r552203-win64) is 32 bit and is actually Version `68.0.3400.0`.

About Chromium:
![chrome_2018-04-22_19-04-20_qos](https://user-images.githubusercontent.com/7304212/39097689-f9d42554-465f-11e8-86c8-7320dcee4b7d.png)

Task Manager:
![taskmgr_2018-04-22_19-04-53_bn7](https://user-images.githubusercontent.com/7304212/39097700-1659f8f2-4660-11e8-8abc-b0ecb1c3f6f2.png)

**Comment by RobRich999** [comment]
Pushed a fresh build with the correct files. Should now be resolved. Thanks!
