### ISSUE TITLE
Why does the .deb package install google's chrome repo?

### ISSUE THREAD

**Issue by pitsi** [RobRich999/Chromium_Clang#20]
I found your chromium build a few hours ago and I gave it a try. And I just noticed that, for some weird reason, it also installs google's repo for chrome (any version, stable, beta and unstable). Why is that? What purpose does it serve other than... maybe compare the unstable version of chrome to the one of your chromium build?

```
$ cat /etc/apt/sources.list.d/chromium-browser-unstable.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
```
Debian testing/unstable x64.

**Comment by RobRich999** [comment]
Chromium does that by default when generating the .deb package installer. Probably because the same script is being used to generate Chrome builds. I probably can edit it out in the source, but I have never bothered. I might take a look for the next round of Linux builds.

**Comment by pitsi** [comment]
Please consider doing the relevant changes in the postinst (or any other script that is executed before or after the installation or removal of the package). For instance, the postinst script, which adds google's apt repo, also adds its key, a cron job etc.

**Comment by RobRich999** [comment]
Should be resolved. Let me know if otherwise. Thanks!

**Comment by pitsi** [comment]
It seems fine. The postrm however has some bits that remove google's repo and its key upon removal of the package. Let's hope it won't affect someone that also has chrome and its repo.

**Comment by RobRich999** [comment]
Sure enough, I did not think about package uninstallation. I will add that to my list for the next round of builds. Thanks again.
