### ISSUE TITLE
VAAPI broken in latest builds?

### ISSUE THREAD

**Issue by Paukan777** [RobRich999/Chromium_Clang#21]
Just discovered that 95 linux builds doesn't have vaapi support (even h264 renders with FFMpeg). Downgraded to 94 and h/w decoding works well.

**Comment by RobRich999** [comment]
I just pushed v96.0.4646.0-r922557 builds. Let me know if still not working. Thanks!

**Comment by Paukan777** [comment]
looks like it works for now

**Comment by RobRich999** [comment]
Thanks for verifying. Odds are I simply forget the source edit for VAAPI enablement in the previous round of builds.
