### ISSUE TITLE
[Question] Was the flag about smooth scrolling removed in v96?

### ISSUE THREAD

**Issue by pitsi** [RobRich999/Chromium_Clang#22]
One of the things I hate in every single chromium based browser is smooth scrolling, because it brings that slow scroll feeling of mobile devices. And I disable it via chrome://flags/#smooth-scrolling.
I admit that I did not check that flag after installing your chromium build, although I did enable the one for the side panel and disabled the tab previews on hover.

Today I noticed that slow scroll in chromium, and I went straight to chrome://flags to change it, but the flag is no longer there. Has it been removed from upstream? It is available on chrome dev (google-chrome-unstable package), but this is on v95 as of today.

Debian testing/unstable x64 running your chromium v96.0.4646.0 r922557 sse3 build.

**Comment by pitsi** [comment]
Chrome dev was updated to v96 (96.0.4651.0) earlier, so I installed it. And the flag is available there as seen in the screenshot.

![2021-09-24-200924_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/134714881-11b5843e-fea1-4ada-83b5-ed0e82649607.png)

If it is some build parameter that affects your build of chromium, can you please re-enable it?

**Comment by RobRich999** [comment]
Nothing I changed. Checked here, and yeah, it is not in this system's installed r922556 revision. I was able to restore it via:

chrome://flags/#temporary-unexpire-flags-m95

I suppose it could have been deprecated accidentally or project devs changed their minds if it has returned in a later revision. Stranger things have happened. ;)

**Comment by pitsi** [comment]
I don't blame you. Let's hope it will be available in your next build. I will use the workaround you mentioned until then.

**Comment by Alex313031** [comment]
It is back as of 96.0.4653.2.  @pitsi 
Also since you don't have a discussions, @RobRich999  I'd like to let you know that I made a chromium fork and you are acknowledged at the end of the readme.md.
Take a look here > [https://github.com/Alex313031/Technetium](url)
Also, is there a place where we could talk without me just butting into comments or making issues.

**Comment by RobRich999** [comment]
> I don't blame you. Let's hope it will be available in your next build. I will use the workaround you mentioned until then.

Confirmed it is back in r925087.

**Comment by RobRich999** [comment]
> It is back as of 96.0.4653.2. @pitsi
> Also since you don't have a discussions, @RobRich999 I'd like to let you know that I made a chromium fork and you are acknowledged at the end of the readme.md.
> Take a look here > [https://github.com/Alex313031/Technetium](url)
> Also, is there a place where we could talk without me just butting into comments or making issues.

Congrats, and thanks! :)

**Comment by RobRich999** [comment]
Oh yeah, the comments section at woolyss.com is a good place to find me, plus it allows others to continue learning about building Chromium Otherwise, my github username @ gmail.com works, too.

**Comment by pitsi** [comment]
While I am waiting for the linux build to show up, allow me one question because it does not worth opening a new issue about it.
On every linux-related release, there is this line about libc
`Please note libc 2.36.1 or later is required.`
The most recent version of libc from upstream is 2.34 as you can see here, yet the package can be installed and works fine even on my system which is now on libc 2.32.
https://www.gnu.org/software/libc/libc.html

Do you mean some other lib?

**Comment by RobRich999** [comment]
It looks like the version was being pulled from ld --version instead of lld --version. ;)

I am somewhat surprised glibc 2.32 works. Chromium must not active use anything introduced in the 2.34 revision.

**Comment by RobRich999** [comment]
I removed the libc notes for the last couple of Linux build revisions.

BTW, I hope to have updated Linux builds today or tomorrow. I have migrated my build box base to 22.10, though I do use use the mainline kernel, a few PPAs, etc.

**Comment by pitsi** [comment]
Ldd is part of libc and its latest version is 2.34 as I mentioned above.
Ld is part of binutils and its latest version is 2.37.
https://www.gnu.org/software/binutils/

**Comment by RobRich999** [comment]
Probably was half asleep when I typed that, though I typo lots of stuff anyway. ;p

Also, yeah I know. I was accidentally pulling the version string from ld instead of ldd when formatting the git submission.

For reference is case anyone else is following along, 21.04 default was glibc 2.33 and 21.10 default is glibc 2.34.
