### ISSUE TITLE
Try something out for me and more questions on AVX

### ISSUE THREAD

**Issue by Alex313031** [RobRich999/Chromium_Clang#25]
1.) I currently have only avx hardware (using an AMD FX-8370 OC'd to 4.5Ghz which takes 3+ hours to compile lol).
OK a little backstory. Google made a chrome app that functioned as an IDE with git integration for chromium and chromiumos.
Codenamed "spark" it was shown here > [https://www.chromium.org/chromium-os/developing-apps-on-your-chromium-os-device](url) (the first link). It was all but abandoned in late 2017. Searching the actual webstore ID number led to a few honorable mentions across the web and it was used by chromium app devs.. There is a source code archive at [https://github.com/googlearchive/chromedeveditor](url) but it is actually many versions behind the last available one, which I got as a .crx from [https://www.crx4chrome.com/apps/pnoffddplpippgcfjdhbmhkofpnaalpg/](url). I then found that most of what would be needed to resuscitate it can be found by just unpacking it (7zip will handle the hidden metadata file). I have made a fork and I would like someone to try it on win 10 with the latest avx chromium. Instructions are in the readme but you probably already know i.e. chrome://extensions, enable dev mode, then drag n drop .crx.
If you wanna try and see how it fares it's at > [https://github.com/Alex313031/Chromium-Dev-Editor](url)

2.) I know you have your avx2 patchset for win, but what would I do to enable just regular avx. It seems just editing //chromium/src/build/config/compiler/BUILD.gn isn't enough like it is on linux. I went ahead and downloaded the avx2 patch and looked at //chromium/src/build/config/win/BUILD.gn and used winmerge (highly reccommended for github-like diff comparisons, better than git-gui and windiff) to see the differences, and there were really only three sections. I changed out  /AVX2 for /AVX and set the ldflags to march:-mavx but it gives errors. What is the proper process for enabling avx with full propogation for all targets?

3.) Maybe this will sound dicky and maybe you have a reason, but have you considered opening a discussions for your repos so that stuff like this could be better handled. I just would like to be able to communicate with you because you've taught me things I couldn't find anywhere else, and you seem to know alot about codegen and compiler shiznit.

Also if all this is annoying just tell me so because this issue isn't exactly kosher or really an issue on your part at all. Although look at my widevine issue that is a real issue.

**Comment by RobRich999** [comment]
You are not bugging me. I have created an issue labeled discussion. I will close this issue and reply there.

https://github.com/RobRich999/Chromium_Clang/issues/26
