### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by wooque** [RobRich999/Chromium_Clang#27]
If builds are published on Flathub it would be easier to install it on any distro and also it will increase trust as Flathub can build it from source

**Comment by RobRich999** [comment]
I appreciate suggestions, though I will have to pass on this one. I have near zero use for Flatpak, plus Flathub would require me maintaining a full git repository. Too much work for a casual hobby IMO.

Just like with my Windows builds, my Linux builds are what I use personally. All my Linux systems support deb packages. If desired, one should be able to use alien to convert deb to rpm or whatever supported package format anyway. ;)

**Comment by Alex313031** [comment]
@wooque you can also extract the .deb and then extract the data.tar.xz and copy the the contents of //opt wherever you want and run the ./chrome executable. This works on distros not supporting .deb packages.
