### ISSUE TITLE
"Utility: Network Service" takes up 500,000+ K of memory

### ISSUE THREAD

**Issue by opusforlife2** [RobRich999/Chromium_Clang#28]
Hi. Thank you for your builds!

I use the chrlauncher version of your browser through woolyss. In most versions, Chromium takes up around 1 GB of RAM, and this particular service seems to take up the largest share, as shown in Chromium's own Task Manager.

But after every few versions, there comes a version where it takes up only 200 MB or so of RAM. And the browser works perfectly well even then.

Any idea what might be causing this bloated memory usage in most versions?

**Comment by RobRich999** [comment]
Welcome! :)

I have no immediate insight. I suppose it could be an origin trial or similar setting a network-related internal feature flag. It could be also a feature being rolled out, then reverted for whatever development reasons, which does happen often with dev builds.

You might find something in the bug reports:

https://bugs.chromium.org/p/chromium/issues/list

**Comment by opusforlife2** [comment]
Okay, thank you. May I ask what your normal RAM usage is with just a new tab opened in Chromium?
