### ISSUE TITLE
Rust optimization, and welcome back.

### ISSUE THREAD

**Issue by Alex313031** [RobRich999/Chromium_Clang#29]
![sponge-bob-square-pants-flying-dutchman](https://user-images.githubusercontent.com/45863095/188048615-306d8fc7-e4bc-4554-b339-383b5e9d7f12.gif)

I have some rust optimizations that I have added to my main build.gn that I would like to share with you. 

Also, I emailed you about the instr-import* stuff, and we can also talk about it here.

Lol i like spongebob

**Comment by RobRich999** [comment]
Thanks. :) I have been passing rust cpu and/or feature flags for awhile now.

Hopefully I will get updated modified build files uploaded in upcoming few days.
