### ISSUE TITLE
v113.0.5664.0-r1119122-linux64-deb-avx2 is broken

### ISSUE THREAD

**Issue by ms178** [RobRich999/Chromium_Clang#33]
Hi @RobRich999,

I've tried out your latest AVX2 Linux build (v113.0.5664.0-r1119122-linux64-deb-avx2) but unfortunately it errors out with "error 4" as soon as I want to change some settings with `about:flags` or see what's going on in `about:gpu`.

The previous build (v113.0.5631.0-r1113127-linux64-deb-avx2) doesn't have this issue.

CPU: Haswell-EP
GPU: AMD Vega 64
OS: CachyOS with latest LLVM-17-git and Mesa-git

As a sidenote: Having Google Sync working would be an important comfort feature for me to have. It would be great if you could get that to work in a future build.

**Comment by RobRich999** [comment]
@ms178 r1119122 seems to be flaky on Linux. Updated build here....

https://github.com/RobRich999/Chromium_Clang/releases/tag/v114.0.5684.0-r1123588-linux64-deb-avx2

....though note it might have some optimization quirks. Details:

https://chromium.woolyss.com/#comment-8859

You can enable Google Sync by creating and setting your own Google API keys. More info:

https://chromium.woolyss.com/#google-api-keys

Once you have keys, you could add the variable exports to /etc/environment for system-wide persistence, or add them wherever else your particular distro recommends for user-specific persistence.

**Comment by ms178** [comment]
Thanks, Rob. I've now tested [114.0.5705.0-r1127992-linux64-deb-avx2](https://github.com/RobRich999/Chromium_Clang/releases/tag/v114.0.5705.0-r1127992-linux64-deb-avx2) and it works fine. It even beats the x86-64-v3 experimental build of Thorium in WebGL Aquarium by a small margin. That's where your build usually performed worse before.

Unfortunately, the Google Sync via API key method is way too complicated for me. If there was one thing still left, I'd say porting the work done by Thorium to get that working comfortably would be a great addition.
