### ISSUE TITLE
v114.0.5732.0-r1134387-win64-avx crash

### ISSUE THREAD

**Issue by jmali86** [RobRich999/Chromium_Clang#34]
Hello.

v114.0.5732.0-r1134387-win64-avx crash/won't open on my laptop, I'm using Win11 x64, everything was fine with 5716 and olders, I have no idea why.

**Comment by RobRich999** [comment]
Thanks for the FYI. I have retracted the affected Windows builds for now.

Similar reports:

https://chromium.woolyss.com/#comment-8984
https://chromium.woolyss.com/#comment-8985
