### ISSUE TITLE
Ctrl-D with --disable-sync flag crashes app

### ISSUE THREAD

**Issue by necros2k7** [RobRich999/Chromium_Clang#39]
@RobRich999 subj

**Comment by Alex313031** [comment]
@necros2k7 Sync is already disabled in his builds since he doesn't include API keys. No need for the cmdline flag.

**Comment by RobRich999** [comment]
@necros2k7 Alex is correct. You can enable sync in builds by adding API keys to your environment variables, but otherwise, it is disabled by default. Toss the flag. ;)
