### ISSUE TITLE
gmail

### ISSUE THREAD

**Issue by uBlock-user** [RobRich999/Chromium_Clang#4]
@RobRich999 

Can't login to gmail or my google account because of NoSync via - https://mail.google.com/mail/

Why ? This didn't happen before, it's now as if I can't access any Google services with my account.

This is what happens - https://i.gyazo.com/b700d988163c5f7c62a513b24b2d2b0e.png

**Comment by RobRich999** [comment]
It is a known problem in Chromium. Has happened before. The workaround is to disable the account consistency flag setting.

chrome://flags/#account-consistency

I will see about digging up the old Chromium bug report and updating it. Thanks!

**Comment by uBlock-user** [comment]
Thanks a lot, I was about to remove your builds, because this is a deal breaker if I can't access gmail and other such services.

**Comment by RobRich999** [comment]
Took a look. The project is finally rolling out DICE, an updated authentication process for Google services. You might eventually have to tweak the flag to "prepare migration...." or "fix auth errors" in the near future.

**Comment by uBlock-user** [comment]
Yeah I tweaked and experimented a bit and it works. Would you mind doing SYNC builds ?

**Comment by RobRich999** [comment]
I do not use Google API keys, thus the reason for no sync support.

**Comment by uBlock-user** [comment]
What I meant is would you do it for the users like me and others, even though you don't use them.

**Comment by RobRich999** [comment]
Probably not at this time, but I will put on the consideration list.

For the most part, ya'll get the same builds I personally use. ;)

**Comment by uBlock-user** [comment]
Thanks, I hope you consider it and let me know when you do.

**Comment by RobRich999** [comment]
Quick FYI. My latest Windows builds (and soon Linux) now include a modification to force "dice_fix_auth_errors," which resolves the Google login issue (for now) without having to set a custom flag.

**Comment by uBlock-user** [comment]
just an FYI - your latest build has chrome://history/ page broken, browsing history doesn't appear when opened - https://i.gyazo.com/3c9bb78f43d7b8cf062afdaeafb49f5f.png

**Comment by RobRich999** [comment]
I have a new build out. Appears resolved, so it was likely a revision issue.

**Comment by RobRich999** [comment]
Working here. Check extensions and any related flags.

**Comment by uBlock-user** [comment]
I only have three extensions, disabled all of them and no change. 

About flags, I have - Smooth Scrolling, QUIC, TLS 1.3, Autoplay Policy, Block Tab-unders. None of them have ever did this before. 

I'm on Windows 10 Pro x64 1803 build FYI

**Comment by uBlock-user** [comment]
I disabled all of those flags and rebooted Chromium, still the same. This is something screwed up with Chromium itself, because `68.0.3440.0-r561732-win64` works fine with the same settings.

**Comment by RobRich999** [comment]
I can not replicate the issue here. Have you checked https://www.crbug.com for a related bug report?

**Comment by uBlock-user** [comment]
Okay, I finally managed to fix this issue. Here's what happened -- Back when I first reported about the [broken history page](https://github.com/RobRich999/Chromium_Clang/issues/4#issuecomment-394142437) the issue did exist, but like as you said in the subsequent [post](https://github.com/RobRich999/Chromium_Clang/issues/4#issuecomment-394142437), it was indeed a revision issue and was fixed in the subsequent build, but any subsequent builds wouldn't work for me, because that bugged build corrupted my browsing data. 

So no matter which build I ran, it always ended with the same result, so I decided to delete all my browsing data. Lo! and Behold!, it's working normally and history's showing up now, so bad builds CAN corrupt your browsing data/history which will cause the issue to persist further, fortunately deletion took care of that for good.

**Comment by eladkarako** [comment]
note that this flag was removed from <code>chrome://flags</code>, but the command-line switch should still work:<br/><code>--disable-account-consistency --disable-features=AccountConsistency</code><br/><sub>or <code>--disable-account-consistency "--disable-features=AccountConsistency<strong>,MobileIdentityConsistency"</strong></code></sub><br/><br/><sup><sub><em>just in-case you've found this through Google search...</em></sub></sup>
