### ISSUE TITLE
"Aw, snap!" when clicking a dropdown menu 

### ISSUE THREAD

**Issue by vlnka** [RobRich999/Chromium_Clang#40]
Version 122.0.6256.0, Windows 10, AVX2 build
[chrome_k2bFcJyEnq.webm](https://github.com/RobRich999/Chromium_Clang/assets/57315687/f0876096-6beb-48c7-95b2-c31380ab996e)

**Comment by RobRich999** [comment]
@vinka Likely revision related. I just kicked off a new round of builds.
