### ISSUE TITLE
Mac Passkeys issue

### ISSUE THREAD

**Issue by zigimike077** [RobRich999/Chromium_Clang#41]
Hi,

Anyone knows why Chromium build using following build argument can't enroll for mac biometric password authentication?

target_cpu="arm64"
#thin_lto_enable_optimizations = true
chrome_pgo_phase = 2
is_official_build = true
is_debug = false

**Comment by RobRich999** [comment]
As a preface, I do not use the biometric feature, and I do not build for MacOS.

That said, off the top of my head, are you setting Google API keys? I think they are required for the feature to work.

https://chromium.woolyss.com/#google-api-keys
