### ISSUE TITLE
Latest chrome.zip build  is the older version 72.0.3612.0 

### ISSUE THREAD

**Issue by uBlock-user** [RobRich999/Chromium_Clang#5]
as the title says, the upload is a screwup. Please upload the latest one.

**Comment by uBlock-user** [comment]
See 

https://chromium.woolyss.com/#comment-4044
https://chromium.woolyss.com/#comment-4044

**Comment by HitomiTenshi** [comment]
And it's 32 bit instead of 64 bit:

![chrome_2018-11-27_18-51-03](https://user-images.githubusercontent.com/7304212/49101063-9cc43580-f275-11e8-9ed2-b727a41c73ab.png)

The same issue happened before with #2

**Comment by uBlock-user** [comment]
Fixed.
