### ISSUE TITLE
v81.0.4027.0-r730928-win32 is actually 64 bit

### ISSUE THREAD

**Issue by lllaffer** [RobRich999/Chromium_Clang#8]
Download of

	https://github.com/RobRich999/Chromium_Clang/releases/download/v81.0.4027.0-r730928-win32/chrome.zip
											    =====			<<<

leads to

	"This version of chrome.exe is not compatible with the version of Windows you're running. 
	 Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) verion of the program,
	 and then contact the software publisher."

...

	Sigcheck "x:\chrome.exe"
	:	
	x:\chrome.exe:
	        Verified:       Unsigned
	        Link date:      00:15 14.01.2020
	        Publisher:      n/a
	        Company:        The Chromium Authors
	        Description:    Chromium
	        Product:        Chromium
	        Prod version:   81.0.4027.0
	        File version:   81.0.4027.0
	        MachineType:    64-bit											<<<
				======

thx for your work

**Comment by RobRich999** [comment]
Build retracted. Thanks for the FYI.
